// src/app/VirtualPatient.ts
//
// Entry point for the virtual patient detail page (patient_virtual.html).
// Connects Firebase to the DashboardController via EventBus.
//
// Data source: Python patient_simulator.py → Firebase → Python app.py processor
//   → /patients/Patient_01/dashboard/current → this page
//
// Patient_01 is a fully simulated patient. All vitals and ECG data are
// generated by simulators/patient_simulator.py and processed by the
// Python backend exactly like a real patient would be.

import { EventBus } from "@app/EventBus";
import { DashboardController } from "@app/DashboardController";
import { setupThemeToggle } from "@ui/components/ThemeToggle";
import { FirebaseService } from "@core/services/FirebaseService";
import type { DashboardPayload } from "@core/models/DashboardPayload";

// Initialize theme toggle (reads saved preference from localStorage)
setupThemeToggle();

const eventBus = new EventBus();
const dashboardController = new DashboardController(eventBus);
dashboardController.bind();

const firebase = new FirebaseService();

// Subscribe to the processed dashboard data written by the Python processor.
// The processor reads raw sensor data, runs ECG analysis, evaluates alerts,
// and writes the result to this path once per POLL_INTERVAL_SECONDS.
firebase.subscribe<DashboardPayload>(
  "/patients/Patient_01/dashboard/current",
  (payload) => {
    if (!payload) return;

    // Forward the payload to all UI components via EventBus
    eventBus.emit<DashboardPayload>("dashboard:update", payload);

    // Update the last-update timestamp in the footer
    const lastUpdate = document.getElementById("last-update");
    if (lastUpdate) {
      lastUpdate.textContent = `Last update: ${
        payload.timestamp ? new Date(payload.timestamp).toLocaleTimeString() : "--"
      }`;
    }
  }
);